#!/bin/bash
CC=gcc
CFLAGS="$CFLAGS -fPIC -g"

mkdir -p .build.sys .build.usr

for i in *.sys.c; do
	j=$(echo $i | sed 's/\.sys\.c//')
	SYS=("${SYS[@]}" "$j")
	SYSOBJ=("${SYSOBJ[@]}" ".build.sys/$j.o")
done

for i in *.usr.c; do
	j=$(echo $i | sed 's/\.usr\.c//')
	USR=("${USR[@]}" "$j")
	USROBJ=("${USROBJ[@]}" ".build.usr/$j.o")
done

cat > Makefile << EOF
all: libjudge.sys.so libjudge.usr.so test

clean:
	-rm -f libjudge.sys.so libjudge.usr.so
	-rm -f ${SYSOBJ[@]} ${USROBJ[@]} test crt.o

crt.o: crt.s
	as -o \$@ \$<

test: test.c crt.o
	$CC -o \$@ \$^ ${CFLAGS} ${LDFLAGS} -nostdlib -I. -L. -ljudge.usr -Wl,--rpath=.

libjudge.sys.so: ${SYSOBJ[@]}
	$CC -shared -o \$@ \$^ ${CFLAGS} ${LDFLAGS}

libjudge.usr.so: ${USROBJ[@]}
	$CC -shared -o \$@ \$^ ${CFLAGS} ${LDFLAGS} -I. -L. -ljudge.sys -Wl,--rpath=.

EOF

echo Building sys deps
mkdir -p .build.sys
for i in ${SYS[@]}; do
	echo Building $i deps
	dep=(`gcc -MM $i.sys.c | sed 's/.*://'`)
	cat >> Makefile << EOF
.build.sys/${i}.o: ${dep[@]}
	$CC -c -o \$@ \$< ${CFLAGS}
EOF
done

echo Building usr deps
mkdir -p .build.usr
for i in ${USR[@]}; do
	echo Building $i deps
	dep=(`gcc -MM $i.usr.c | sed 's/.*://'`)
	cat >> Makefile << EOF
.build.usr/${i}.o: ${dep[@]}
	$CC -c -o \$@ \$< ${CFLAGS}
EOF
done